import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Item, { SmallItem } from '../components/Item'
import { FaPlay } from 'react-icons/fa'
import { Swiper, SwiperSlide } from "swiper/react"
import "swiper/css";
import "swiper/css/pagination";
import { Pagination } from "swiper";
import Countdown from 'react-countdown';

const DATA1 = ['/xbanner.webp', '/xfeature1.webp', '/xfeature2.webp', '/xfeature3.webp', '/xfeature4.webp', '/xoffer.webp', '/xclient1.webp', '/xclient2.webp', '/xclient3.webp', '/xclient4.webp', '/xclient5.webp',]
const DATA2 = ['/xproduct_1.webp', '/xproduct_2.webp', '/xproduct_3.webp', '/xproduct_4.webp']
const DATA3 = ['/xproduct_1.webp', '/xproduct_2.webp', '/xproduct_3.webp', '/xproduct_4.webp', '/xproduct_5.webp', '/xproduct_6.webp']

const Slider = () => <div className='grid grid-cols-1  lg:grid-cols-3 bg-myblue items-center justify-items-center py-5 px-4 lg:px-[10vw] ' >
  <div className='mt-32 h-[35vh] ' >
    <h1 className='font-bold text-4xl lg:text-4xl mb-2' >Wood & Cloth Sofa</h1>
    <p>Our range of sofa set options is truly all-encompassing and features choices like solid wood sofas, leather sofa sets, and many others.</p>
    <span className='btn rounded p-2 my-4 inline-block ' > <Link href='/shop'> BUY NOW  </Link></span>
  </div>
  <span className='p-8 hidden lg:block col-span-2 '>
    <Image width={300} height={300} src='/xbanner.webp' alt='Featured Image' />
  </span>
</div>

const renderer = ({ days, hours, minutes, seconds }) => <div className='flex justify-around mx-4 items-center text-center my-8' >
  <p>DAYS  <span className='block text-3xl font-extrabold' >{days}</span></p>
  <p>HOURS  <span className='block text-3xl font-extrabold' >{hours}</span></p>
  <p>MINUTES  <span className='block text-3xl font-extrabold' >{minutes}</span></p>
  <p>SECONDS  <span className='block text-3xl font-extrabold' >{seconds}</span></p>
</div>

export default function Home({ data, smallData, item }) {

  return (
    <>
      <Head>
        <title>Aranoz.
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*HERO SECTION  */}
      <Swiper
        slidesPerView={1}
        spaceBetween={30}
        loop={true}
        autoplay={true}
        pagination={{
          clickable: true,
        }}
        modules={[Pagination]}
        className="mySwiper"
      >

        <SwiperSlide><Slider /> </SwiperSlide>
        <SwiperSlide><Slider /> </SwiperSlide>
        <SwiperSlide><Slider /> </SwiperSlide>
      </Swiper>

      {/* FEATURED SECTION */}
      <h1 className='font-bold text-3xl my-8 text-center' >Featured Category</h1>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4  items-center my-10 lg:px-[10vw]">

        <div className='my-4 bg-[#e2eeff] p-8 lg:col-span-2 m-4 ' >
          <p className='-mt-4' >Premium Quality</p>
          <h1 className='text-2xl font-bold mb-4' >Latest foam Sofa</h1>
          <div className='flex justify-end ' >
            <Image src={data[1]} width={300} height={300} alt='Featured Images 1' />
          </div>
          <p className='text-mypink -mb-4' >Explore Now <FaPlay className='inline ml-2' /> </p>
        </div>

        <div className='my-4 bg-[#e2eeff] p-8 m-4 lg:m-0 ' >
          <p className='-mt-4' >Premium Quality</p>
          <h1 className='text-2xl font-bold mb-4' >Latest foam Sofa</h1>
          <div className="flex justify-end">
            <Image src={data[2]} width={300} height={300} alt='Featured Images 2' />
          </div>
          <p className='text-mypink -mb-4' >Explore Now <FaPlay className='inline ml-2' /> </p>
        </div>

        <div className='my-4 bg-[#e2eeff] p-8 m-4 lg:m-0 lg:ml-4' >
          <p className='-mt-4' >Premium Quality</p>
          <h1 className='text-2xl font-bold mb-4' >Latest foam Sofa</h1>
          <div className="flex justify-end">
            <Image src={data[3]} width={300} height={300} alt='Featured Images 3' />
          </div>
          <p className='text-mypink -mb-4' >Explore Now <FaPlay className='inline ml-2' /> </p>
        </div>

        <div className='my-4 bg-[#e2eeff]  p-8 lg:col-span-2 m-4 ' >
          <p className='-mt-4' >Premium Quality</p>
          <h1 className='text-2xl font-bold mb-4' >Latest foam Sofa</h1>
          <div className="flex justify-end">
            <Image src={data[4]} width={300} height={300} alt='Featured Images 4' />
          </div>
          <p className='text-mypink -mb-4' >Explore Now <FaPlay className='inline ml-2' /> </p>
        </div>
      </div>

      {/* AWESOME SECTION */}
      <div className='text-3xl font-bold lg:mx-[10vw] pl-4 ' >Awesome <span className='text-gray-400 ml-5' >Shop</span> </div>
      <Item img={item} />

      {/* WEEKEND SALE */}

      <div className='grid grid-cols-1 items-center lg:grid-cols-2 bg-myblue py-8' >
        <div className='m-4 text-center' >
          <Image src={data[5]} height={300} width={300} alt={'xOffer Image'} />
        </div>
        <div  >
          <h1 className='font-bold text-5xl my-8 text-center mb-4' >Weekly Sale on 60% Off All Products</h1>
          <Countdown date={Date.now() + 9.504e+7} renderer={renderer} />
          <p className='mb-1 text-center' > <input type="text" className='py-4 px-2 lg:px-8   bg-white rounded outline-none' placeholder='Email Address' /> <button className='btn rounded p-4 -ml-1 px-2 lg:px-8 ' >BOOK NOW</button> </p>
        </div>
      </div>
      {/* BESTSELLER */}
      <div className='text-3xl font-bold lg:mx-[10vw] pl-4 my-10 ' >BestSeller <span className='text-gray-400 ml-5' >Shop</span> </div>
      <SmallItem img={smallData} />

      {/* SUBSCRIBE */}
      <div className='bg-area bg-cover h-[70vh] text-center flex flex-col justify-center items-center gap-10 ' >
        <p className='font-semibold text-lg text-mypink' >JOIN OUR NEWSLETTER</p>
        <h1 className='text-3xl lg:text-5xl font-bold' >Subscribe to get Updated <br /> with new offers</h1>
        <p className='mb-1 text-center' > <input type="text" className='py-4 px-2 sm:px-8  bg-white rounded outline-none' placeholder='Email Address' /> <button className='btn rounded p-4 -ml-1 px-2 sm:px-6' >SUBSCRIBE NOW</button> </p>
      </div>

      {/* WORKED WITH CLIENT */}
      <div className='grid grid-cols-4 lg:grid-cols-5 justify-items-center my-10 gap-6 m-4 ' >
        <div> <Image src={data[7]} width={100} height={100} alt="client" /> </div>
        <div> <Image src={data[6]} width={100} height={100} alt="client" /> </div>
        <div> <Image src={data[8]} width={100} height={100} alt="client" /> </div>
        <div> <Image src={data[7]} width={100} height={100} alt="client" /> </div>
        <div> <Image src={data[9]} width={100} height={100} alt="client" /> </div>
        <div> <Image src={data[6]} width={100} height={100} alt="client" /> </div>
        <div> <Image src={data[8]} width={100} height={100} alt="client" /> </div>
        <div> <Image src={data[10]} width={100} height={100} alt="client" /> </div>
        <div> <Image src={data[7]} width={100} height={100} alt="client" /> </div>
        <div> <Image src={data[10]} width={100} height={100} alt="client" /> </div>
        <div className='lg:hidden'> <Image src={data[9]} width={100} height={100} alt="client" /> </div>
        <div className='lg:hidden' > <Image src={data[7]} width={100} height={100} alt="client" /> </div>
      </div>

    </>
  )
}
export async function getStaticProps() {

  return {
    props: {
      smallData: DATA2,
      item: DATA3,
      data: DATA1
    }
  }
}